[package]
name = "paguroidea"
version = "0.1.0"
authors = ["Alec Deason <alec@tinycountry.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
pest = "2"
pest_derive = "2"
rodio = "0.11"
rand = "0.7"
